### ISSUE TITLE
单价周本 - 数量显示有误

### ISSUE THREAD

**Issue by AndrewLaBabies** [OctoberCK/genshinhelper#12]
![650DB9E5-4291-43EF-9B9B-6DE50E4AC4A6_1_201_a](https://user-images.githubusercontent.com/8588393/170879358-555a1209-bb7e-4f5f-9acc-d64764dfd3f7.jpeg)

![5128AA26-EF99-4C06-81C0-8AACBC27CF7F_1_201_a](https://user-images.githubusercontent.com/8588393/170879369-b35bb1f5-4cd0-4a34-ab30-94b9c454ea78.jpeg)

**Comment by OctoberCK** [comment]
这不是有误，我修改了显示的逻辑，现在是 已完成/总数 而不是 剩余次数/总数，为了和其他几个模块显示的逻辑一致。
