### ISSUE TITLE
小组件细节调整建议，参考评论内容

### ISSUE THREAD

**Issue by wwWATERS** [OctoberCK/genshinhelper#22]

**Comment by wwWATERS** [comment]
背景的切图像素有点不够，需要倍数扩大一点，有点糊

**Comment by OctoberCK** [comment]
依次回复一下：
1. 由于树脂和宝钱的模块和每日委托的模块比例不一致，完全对齐反而会导致有大片的空白和比例不协调。目前打算稍微放大一些树脂和宝钱的图标，并将显示的数字放大到极限来缓解这个问题。
2. 斜杠在这里实际上是一个贴图，和上面的数字间隔较大其实是字重的原因，斜杠贴图不能入侵上方数字的显示范围，而字重越大实际上数字边缘的冗余空间也越多，导致了这个问题，暂时没有好的解决方案，我这里没有人为加入任何间隔。
3. 暂时没有遇到必须要减少文字来挤压空间的情况，到期时间显示的形式我更倾向于现在这种。
4. 这是iOS的一个奇怪的bug，我用的切图其实全部都是Retina级别的，你可以到Scriptable软件内部去运行一下看看，那里的渲染是正常的，但放到桌面上就会变糊。
5. 这个建议会尽可能调整采纳，因为小块的圆角一旦过大会显得非常圆，影响美观。
