### ISSUE TITLE
关于每日委托完成情况的判定

### ISSUE THREAD

**Issue by Xm798** [OctoberCK/genshinhelper#25]
如果在他人世界中完成每日委托，那么实时便笺接口仍会显示完成 0 个委托，建议首先根据额外奖励领取情况判断每日委托完成情况，如果领取了额外奖励，那么每日委托必定是已完成的，没有必要再显示 4/4。

**Comment by Xm798** [comment]
> 确实没有考虑过在他人世界完成任务的情况，那如果没有做完4个任务，又是在他人世界完成的，有什么好的显示方法吗？

这个通过便笺接口无法判断，目前只能做到根据额外奖励是否领取来判断当日委托是否全部完成。

**Comment by OctoberCK** [comment]
> > 确实没有考虑过在他人世界完成任务的情况，那如果没有做完4个任务，又是在他人世界完成的，有什么好的显示方法吗？
> 
> 这个通过便笺接口无法判断，目前只能做到根据额外奖励是否领取来判断当日委托是否全部完成。

已经更新优化了这部分的显示了。
