### ISSUE TITLE
显示问题

### ISSUE THREAD

**Issue by JoshYEn** [OctoberCK/genshinhelper#26]
桌面截图如下：
![IMG_1AA533574854-1](https://user-images.githubusercontent.com/11255434/181054021-e3573b0a-622f-430a-882c-14bac75fb684.png)

Scriptable中预览没有问题。

系统：iOS 16 Public Beta

**Comment by OctoberCK** [comment]
部分机型在测试版系统中的UI分辨率有一定的变化，你可以自行修改中号小组件中的infoSize，改小一些即可。
