### ISSUE TITLE
亚服 API / Asia server API

### ISSUE THREAD

**Issue by zhyu** [OctoberCK/genshinhelper#3]
API host: `https://api-takumi.mihoyo.com` ->  `https://bbs-api-os.hoyolab.com`
salt: `xV8v4Qu54lUKrEYFZkJhB8cuOh9Asafs` -> `okr4obncj8bw5a65hbnn5oo6ixjc3l9w`
`x-rpc-app_version`: `2.19.1` -> `2.9.1`
`x-rpc-client_type`: `5` -> `2`
region (`server` parameter when calling `dailyNote` API: `os_asia`

**Comment by OctoberCK** [comment]
Thanks, the code will be synchronized later.
