### ISSUE TITLE
小组件显示NaN

### ISSUE THREAD

**Issue by CoolwindHF** [OctoberCK/genshinhelper#30]

**Comment by CoolwindHF** [comment]
所有的操作都正常操作 uid填写正确 但是所有数据都现实NaN无法显示

**Comment by OctoberCK** [comment]
你这样描述对解决问题是零帮助的，没有任何的截图没有任何的错误信息提供。数据显示NaN基本是cookie不正确导致的。请重新检查cookie是否正确且有效，米游社退出或异地，异设备登录均会导致cookie失效。

**Comment by CoolwindHF** [comment]
![Uploading 13841C19-BA12-4717-AC17-13D8951FF910.png…]()
