### ISSUE TITLE
新号洞天,每日,质量仪未开是不是会导致脚本闪退？

### ISSUE THREAD

**Issue by 2375399351** [OctoberCK/genshinhelper#32]
我试了个小号，但是里面洞天,每日,质量仪未开都没开，运行脚本就闪退了，换老号就正常，ck的格式是一样的，uid也没错

**Comment by OctoberCK** [comment]
重新拉取更新一下，新版本的应该已经不会闪退了。

**Comment by 2375399351** [comment]
> 重新拉取更新一下，新版本的应该已经不会闪退了。

genshinwidget_elite.js
这个脚本，拉取的就是最新版本的，同一个脚本老号就正常显示，新号就闪退，不明白为什么，uid也是改过的

**Comment by OctoberCK** [comment]
> > 重新拉取更新一下，新版本的应该已经不会闪退了。
> 
> genshinwidget_elite.js 这个脚本，拉取的就是最新版本的，同一个脚本老号就正常显示，新号就闪退，不明白为什么，uid也是改过的

请提供更多的信息与截图，我也没有新号做测试，仅仅这样描述没法解决问题。

**Comment by 2375399351** [comment]
> > > 重新拉取更新一下，新版本的应该已经不会闪退了。
> 
> > 
> 
> > genshinwidget_elite.js 这个脚本，拉取的就是最新版本的，同一个脚本老号就正常显示，新号就闪退，不明白为什么，uid也是改过的
> 
> 
> 
> 请提供更多的信息与截图，我也没有新号做测试，仅仅这样描述没法解决问题。

主要我不知道怎么提供啊，就是uid，ck，和服务器信息写好后，按右下角运行，软件就直接闪退了，什么报错或者日记都看不见啊

**Comment by 2375399351** [comment]
> > > 重新拉取更新一下，新版本的应该已经不会闪退了。
> 
> > 
> 
> > genshinwidget_elite.js 这个脚本，拉取的就是最新版本的，同一个脚本老号就正常显示，新号就闪退，不明白为什么，uid也是改过的
> 
> 
> 
> 请提供更多的信息与截图，我也没有新号做测试，仅仅这样描述没法解决问题。

https://api-takumi-record.mihoyo.com/game_record/app/genshin/api/dailyNote?server=cn_gf01&role_id=*******

这是我抓包脚本运行后的连接，里面显示的内容是这些，比大号要少很多内容![image](https://user-images.githubusercontent.com/34334506/183879006-e9bbd94d-e10d-4775-b966-bb743b5c6b38.png)
