### ISSUE TITLE
关于大号组件的问题

### ISSUE THREAD

**Issue by CainLuo** [OctoberCK/genshinhelper#33]
我手头上有iPad Pro 12.9 M1，iPhone 11 Pro Max，iPhone 13 Pro Max，目前发现大号组件有些小问题，无论是genshinwidget_dynamic还是genshinwidget_dynamic_stacked都是如此：

![IMG_5314](https://user-images.githubusercontent.com/8857291/183857532-cb801b98-2515-49f8-8e14-39d1d5729966.PNG)

iPad Pro 12.9 M1的超大号组件更加奇怪：

![iShot_2022-08-10_16 48 03](https://user-images.githubusercontent.com/8857291/183857982-23c9220b-e736-4667-be69-27e65d8255e8.png)

**Comment by OctoberCK** [comment]
如果一定要使用大号小组件，请使用_lite版本的，仅仅只是无法更换背景。dynamic的大号小组件有问题是第三方控件带来的，暂时没空解决。至于iPad上的超大号小组件暂时没有做适配。

**Comment by CainLuo** [comment]
还有一个小问题，最小号的组件，无论是genshinwidget_dynamic_stacked还是genshinwidget_dynamic都是一样的，我用的是整合版本 @OctoberCK

**Comment by OctoberCK** [comment]
> 还有一个小问题，最小号的组件，无论是genshinwidget_dynamic_stacked还是genshinwidget_dynamic都是一样的，我用的是整合版本 @OctoberCK

什么叫都是一样的？没有懂你的意思。
