### ISSUE TITLE
在探索派遣没有全部完成时，将”可领取奖励“改为下一个完成的时间

### ISSUE THREAD

**Issue by mintyknight** [OctoberCK/genshinhelper#34]
在中大小的时候，有了圈圈进度条来显示单人完成情况，所以在不是5人完成的情况下，其实可以清晰得知”可领取奖励“，但无法清晰得知接下来的一个角色完成的时间。
所以我希望改成，全员完成，显示”可领取奖励“，只要有人未完成，显示接下来即将完成的角色的时间（就是类似现在没人完成时显示的）。
如果你觉得这个提议可以的话，我可以去改这个，想先问问你的看法。

**Comment by OctoberCK** [comment]
可以的，这个逻辑确实也挺好的。

**Comment by mintyknight** [comment]
#38
