### ISSUE TITLE
要不要把新设计版当成唯一的正式版，其他的标注为"停止维护“？

### ISSUE THREAD

**Issue by mintyknight** [OctoberCK/genshinhelper#36]
我在B站上看到有人在推广这个小组件，评论里有人用了整合版之类的出了问题，我在想是不是直接只推广新设计的这版，毕竟其他的版本貌似都没有在维护了。如果是的，那可能要更新一下nga.cn帖子和这个的readme文件
还有一点，推荐在这个readme里加上nga.cn的帖子链接，帮助大家更容易的去nga.cn反馈问题啥的（好多人不用github的）

**Comment by mintyknight** [comment]
对了，有啥方便的法子联系你么？除了issues或nga的帖子？

**Comment by mintyknight** [comment]
对了B站的视频名字《超简单的新版ios原神树脂小组件》

**Comment by OctoberCK** [comment]
加我的QQ号吧，495812587。
