### ISSUE TITLE
XS Max上洞天宝钱显示不全

### ISSUE THREAD

**Issue by fairy-ju** [OctoberCK/genshinhelper#37]
![D8DE5458-E75C-4D74-B5E6-37C1AA12AD11](https://user-images.githubusercontent.com/84318632/184470794-18cec30a-2392-448d-a968-835971d57d34.jpeg)

**Comment by OctoberCK** [comment]
这个是由于不同设备的分辨率和ppi不一致导致的，你可以手动微调代码内的这个参数，来获得最合适的效果。
![image](https://user-images.githubusercontent.com/42833426/185796132-3c876af5-e425-4650-8c54-8b78ae4de464.png)

**Comment by fairy-ju** [comment]
> 这个是由于不同设备的分辨率和ppi不一致导致的，你可以手动微调代码内的这个参数，来获得最合适的效果。
> ![image](https://user-images.githubusercontent.com/42833426/185796132-3c876af5-e425-4650-8c54-8b78ae4de464.png)

感谢作者的解答，谢谢
