### ISSUE TITLE
新设计版 失效了

### ISSUE THREAD

**Issue by dale502** [OctoberCK/genshinhelper#44]
用的新设计版，在scriptable删除重新用捷径搞了一遍，报错如图
![IMG_CD0652FB660C-1](https://user-images.githubusercontent.com/69394230/200812589-f814c1ee-86c3-4625-bdb5-bb7e1f3fbfe4.jpeg)

**Comment by dale502** [comment]
试了精简版本，可以运行，但是里面没数据，都是undefine

**Comment by OctoberCK** [comment]
请检查自己的cookie是否有效，以上的报错均为cookie失效或不正确导致，如果cookie正常的话为米哈游1034错误，请到米游社通过验证即可恢复，和组件本身无关

**Comment by dale502** [comment]
> 

打开米游社app，有个提醒的账号异常的验证码，通过后，小组件就恢复了，感谢
